---
- name: Playbook to install Nginx on web servers
  hosts: web_servers    # Specify the group of hosts to run the playbook on
  become: yes           # Use 'sudo' to execute tasks with elevated privileges
  tasks:
    - name: Install Nginx
      apt:               # Use Ansible's 'apt' module for managing packages
        name: nginx      # Name of the package to be installed
        state: present    # Ensure that the package is installed (present)
    - name: Ensure Nginx is started
      service:           # Use Ansible's 'service' module for managing services
        name: nginx      # Name of the service to manage
        state: started    # Ensure the service is running